---
output:
  word_document: default
  pdf_document: default
  html_document: default
---
 ---
title: "R Notebook"
output: html_notebook
---

# Init
```{r setup, include=F, results='hide', message=F, warning=F}
knitr::opts_knit$set(root.dir = normalizePath(".."))


comm.libs <- c("plyr", "tidyverse", "stringr", "ggplot2", "openxlsx")
.tmp <- lapply(comm.libs, require, character.only = TRUE)

set.seed(17)
default.par <- par(no.readonly = TRUE)
options(stringsAsFactors = FALSE)

#ggplot theme set
theme_set(theme_bw())
fontsize = 18L
theme_update(axis.title.x = element_text(size=fontsize))
theme_update(axis.title.y = element_text(size=fontsize))
theme_update(plot.title = element_text(size=fontsize+2))
```

# My pi calculation
## Function that a vector of size N in Norm(mean, std)

```{r}
set.seed(123)


my.norm <- function(mean=0,std=1,N=10000){
  U1 <- runif(N)
  U2 <- runif(N)
  
  # Z0 here follows a standard normal distribution
  Z0 <- sqrt(-2*log(U1)) * cos(2*pi*U2)
  return(Z0*std + mean)
}

x <- my.norm( std= 4)
hist(x, n=100)

mean(x)
sd(x)


# # mean(Z0)
# # sd(Z0)
# # hist(Z0, n=50, col="gray20")
# #distribution ax+b used to transform the standard normal distribution to 
# # N(u, delta^2)
# # tranfrom N(0,1^2) to N(188,41^2)
# srs <- Z0 * 41 + 188
# # n simulate number of beams/bars 
# hist(srs, n=50, col="gray20")
# summary(srs)
# sd(srs)
# 
# srs100 <- sample(srs, size=100, replace=T)
# mean(srs100)
# 
# sim1 <- sapply(1:1000, function(x){
#   rv <- sample(srs, size=100, replace=T)
#   mean(rv)
#   #sample distribution of sample mean
# })
# 
# mean(sim1)
# sd(sim1)
# hist(sim1, n=30, col="gray20")
# #hist(sim1, n=10, col="gray20")
# #mean(sim1 >=185 & sim1<=191)
# mean(sim1 >185 & sim1<191)
# 
# x <- sim1 >185 & sim1<191
# p <- sum(x==T)/length(x)
# p
```
# my Pi calculation
## Makes it so that the same random numbers are generated
```{r, fig.width=6, fig.height=6}
set.seed(123)

N <- 10000
x <- runif(N, -1,1)
y <- runif(N, -1,1)
plot(x,y, pch=".", asp=1)
```

## Produces random points in a 2-by-2 area in the coordinate plane centered around the origin

```{r}
ind <- (x^2 + y^2) <= 1
dat <- data.frame(X=x, Y=y, InCircle=ind)
head(dat)
```

## Finds the points that are within the area of a circle

```{r}
library(ggplot2)
ggplot(dat, aes(x=X, y=Y, col=InCircle)) + geom_point()
#Graphs the circle
my.pi <- mean(ind) * 4
my.pi
#Using the previously generated values, solve for pi

```
```{r}
N <- 100000000
x <- runif(N, -1,1)
y <- runif(N, -1,1)

ind <- (x^2 + y^2) <= 1
(my.pi <- mean(ind) * 4)
#Another method to find pi
(diff <- my.pi - pi)
#Shows the difference between the calculated value of pi and pi to show how close it is
```

```{r}

norm_dist <- function(mean=0,std=1,n=10000){
  U1 <- runif(n)
  U2 <- runif(n)
  #U1 and U2 ard independent variables that are uniformly distributed (0,1) 
  Z0 <- sqrt(-2*log(U1)) * cos(2*pi*U2)
  #Standard Normal Distribution
  #Formula from the box-muller transfrom, is used to create a standard normal distribution
  return(Z0*std + mean)
}

set.seed(123)
#Makes it so the randomized values would be the same for replication

toddler.tv <- norm_dist(mean=25,std=3)
#Uses the function stated earlier in order to create a standard distribution plot with the given mean and standard deviation

tv.sim <- sapply(1:10000, function(x){
  sam_dist_mean <- sample(toddler.tv, size=20,replace =T)
  head(sam_dist_mean)
  mean(sam_dist_mean)
})
#New function performs the Monte Carlo simulation and randomly selects 20 toddlers, finds the average time spent watching tv among them, and repeats it 10,000 times 

```

# use rnorm instead
```{r}
set.seed(321)
N <- 100000
tv.sim2 <- sapply(1:N, function(x){
  s <- rnorm(20, mean=25, sd=3)
  return(mean(s))
})
(t20.prob2 <- mean(tv.sim2 > 26.3))
```

```{r}
#curve(dnorm(x, mean=25, sd=.6208))
# dotchart(floor(tv.sim*10)/10.0 , cex=.5)
hist(tv.sim, n=100, prob=T, main="")
#Produces histogram of the earlier function, graphing a sample distribution of sample means. It is converted into a density plot, making the area beneath the normal curve 1
curve(dnorm(x,mean=mean(tv.sim),sd=sd(tv.sim)), add = TRUE, col=3)
#Normal curve for the histogram
abline(v=26.3, col='purple',lwd=2,lty=2)
#Line that indicates the location of 26.3 hours on the histogram
text(26.7,.4,labels='x>26.3' )
#Displays the text 'x>26.3' next to the above line
plot(x=tv.sim, y=1:length(tv.sim), pch=".")
#Graphs the dotplot for tv.sim
abline(v=26.3, lty=2, col="purple",lwd=2) 
#Graphs the line of x=26.3
t20.prob <- mean(tv.sim > 26.3)
t20.prob
#Calculates the probability of of the mean number of hours spent watching TV is greater than 26.3

```



```{r}
require(plyr)
calc.pi <- function(n=10000, times=3, seed = set.seed(123)){
  rv <- sapply(1:times, function(zz){
    sim <- sapply(1:n, function(x){
      x <- runif(1, -1,1)
      y <- runif(1, -1,1)
      return( (x^2 + y^2) <= 1 )
    })
    my.pi <- mean(sim) * 4
    return(my.pi)
  })
  return(rv)
}

N <- 1:5
rv <- plyr::ldply(N, function(x){
  ss <- calc.pi(n=10^x, times=20)
  return(ss)
})
rv$Simulations <- 10^N
dat <- reshape2::melt(rv, id.vars = "Simulations")

pibox <- ggplot(dat, aes(x=Simulations, y = value, col=factor(Simulations))) + geom_boxplot() + geom_point(pch=1) + scale_x_log10() + geom_hline(yintercept = pi, lty=2) + theme_bw() + labs(y="Value", x="# simulation") + guides(col=FALSE)

ggsave('graphs/PI_Box_plot.png', plot = pibox)
```


