---
title: "R Notebook"
output: html_notebook
---
# Init
```{r setup, include=F, results='hide', message=F, warning=F}
knitr::opts_knit$set(root.dir = normalizePath(".."))


comm.libs <- c("plyr", "tidyverse", "stringr", "ggplot2", "openxlsx")
.tmp <- lapply(comm.libs, require, character.only = TRUE)

set.seed(17)
default.par <- par(no.readonly = TRUE)
options(stringsAsFactors = FALSE)

#ggplot theme set
theme_set(theme_bw())
fontsize = 18L
theme_update(axis.title.x = element_text(size=fontsize))
theme_update(axis.title.y = element_text(size=fontsize))
theme_update(plot.title = element_text(size=fontsize+2))
```
# Network D3

```{r}
library(webshot)
library(htmlwidgets)
library(visNetwork)
# minimal example
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))
v<-visNetwork(nodes, edges)


# visExport(z, type='png', name="export-network",label="save network")

# https://datastorm-open.github.io/visNetwork/more.html
visSave(v, file = "network.html")

# the image takes some time to appear 
# and webshot delay 0.2 second by default, which is not enough in this case
# resolution is not great, though
webshot("network.html", file = "Rplot2.png", delay=2)
```



