#' @title Convert a Mindmap file into a Markdown file.
#'
#' @description This functions will convert a Mindmap file into a Markdown file by looking at the nodes and generate headers based on the nodes present in the Mindmap file. Ignores any addtional output/input/images generated by Print_MM_Map.
#'
#' @param mm_fn Mindmap file that is the input of the function.
#' @param out_rmd_fn Name of the Markdown file that is generated.
#'
#' @return A Markdown file with the content of the Mindmap file.
#'
#' @examples PrintRMDFile(mm_fn = 'Mindmap.mm', out_rmd_fn = 'mm_output.Rmd')
#' @export PrintRMDFile
PrintRMDFile <- function(mm_fn, out_rmd_fn=get_martmi_cfg('rmd_name')){
  out <- ConvertMM(FindMMcode(mm_fn))


  fn <- trimws(out[[1]][[1]])

  rmd_out <- c(
    '---
title: "R Notebook"
output: html_notebook
---',
    unlist(out[-1], r=T)
  )

  writeLines(con = out_rmd_fn, rmd_out)

}
