#' @title Prints the Mindmap.
#'
#' @description Uses the information passed down by rmd_parser to generate the Mindmap. Uses many smaller functions along the way to achieve this.
#'
#' @param rmd_info The list of information generated by rmd_parser. Contains title, filename, and the codeblocks of the Mawrkdown file.
#' @param output.fn The name of the Mindmap file that is produced.
#' @param title The title of the Mindmap that is produced.
#'
#'
#' @return The Mindmap file.
PrintMap <- function(rmd_info, output.fn = get_martmi_cfg('mm_name'), title = get_martmi_cfg('main_title')){
  input2 <- rmd_info
  #following value contains the number of pound signs in each line
  pndloccnt <- nchar(str_extract(input2$header, '^#+'))
  #following value takes the difference of the number of pound signs with the next value, and adds a 1 to ensure that the difference for the last set of pound sign is obtained.
  pnddiff <- diff(c(pndloccnt,1))
  # mindmap <- '<map version ="1.0.1">'


  #following two values are the next two lines for the mindmap file that still require manual input
  #1. Title
  #mindmap <- c(mindmap, startnode(title, endnode=F))
  #2. File name
  mindmap <- c("", startnode(basename(input2$filename), endnode=F))

  #Prints the headers in R without the pound sign from the R code
  realinput <- str_match(input2$header, '^#+ *(.+)')[,2]


  #Where rest of the code is transformed from R code to XML
  #3. Headers
  for (x in 1:length(pnddiff)) {
    if (pnddiff[x] > 0){
      mindmap <- c(mindmap, startnode(input2$header[x], endnode=F, codeblock = input2$codebloc[[x]]))
    }
    else if (pnddiff[x] == 0){
      mindmap <- c(mindmap, startnode(input2$header[x], endnode=T, codeblock = input2$codebloc[[x]]))
    }
    else {
      mindmap <- c(mindmap, startnode(input2$header[x], endnode=T, codeblock = input2$codebloc[[x]]), endnode(-pnddiff[x]))
    }
  }
  #  Puts in remaining ending nodes
  # mindmap <- c(mindmap, endnode(2), '</map>')
  mindmap <- c(mindmap, endnode(1))
  # writeLines(mindmap, output.fn)
  return(mindmap)
}

